name: Deploy DEV to IONOS

on:
  push:
    branches:
      - dev

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.IONOS_FTP_HOST }}
          username: ${{ secrets.IONOS_FTP_USER }}
          password: ${{ secrets.IONOS_FTP_PASS }}
          server-dir: ${{ secrets.IONOS_DEV_REMOTE_PATH }}
          local-dir: ./
          exclude: |
            **/.git*
            **/.github*
